name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm run build --if-present

    - run: npm test

    # Install pa11y and its dependencies
    - name: Install pa11y
      run: npm install -g pa11y

    # Run pa11y and generate a report
    - name: Run pa11y accessibility tests
      run: |
        mkdir -p reports
        pa11y http://localhost:3000 > reports/pa11y-report.txt
      # Replace `http://localhost:3000` with the URL of your built application
      # If your app is not running on port 3000, update the URL accordingly

    # Optionally, upload the pa11y report as an artifact
    - name: Upload pa11y report
      uses: actions/upload-artifact@v4
      with:
        name: pa11y-report
        path: reports/pa11y-report.txt
